builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team

version:
  semver:
    major: 0
    minor: 0

stages:
  build:
    image: alpine:3.9
    commands:
    - echo "nothing to build here, move along..."

releases:
  tooling:
    actions:
    - name: deploy-canary
    - name: deploy-stable
    - name: rollback-canary
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette
        container:
          port: 5000
          repository: library
          name: registry
          tag: 2.7.1
          env:
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /cache-volume
            REGISTRY_HTTP_DEBUG_ADDR: :5001
            REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: true
          liveness:
            path: /
          readiness:
            path: /
          metrics:
            path: /metrics
            port: 5001
          cpu:
            request: 250m
            limit: 1000m
          memory:
            request: 4096Mi
            limit: 4096Mi
        sidecars:
        - type: openresty
          cpu:
            request: 100m
            limit: 200m
          memory:
            request: 200Mi
            limit: 200Mi
        - type: heater
          image: estafette/estafette-docker-cache-heater:dev
          env:
            MTU: 1460
            MIRROR: http://localhost:5000
          cpu:
            request: 100m
            limit: 200m
          memory:
            request: 200Mi
            limit: 200Mi
          securityContext:
            privileged: true
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        configs:
          inline:
            container-list.yaml: |
              containers:
              - extensions/prefetch:dev
              - extensions/prefetch:beta
              - extensions/prefetch:stable

              - extensions/envvars:dev
              - extensions/envvars:beta
              - extensions/envvars:stable

              - extensions/git-clone:dev
              - extensions/git-clone:beta
              - extensions/git-clone:stable

              - extensions/docker:dev
              - extensions/docker:beta
              - extensions/docker:stable

              - extensions/gke:dev
              - extensions/gke:beta
              - extensions/gke:stable

              - extensions/github-status:dev
              - extensions/github-status:beta
              - extensions/github-status:stable

              - extensions/bitbucket-status:dev
              - extensions/bitbucket-status:beta
              - extensions/bitbucket-status:stable

              - extensions/slack-build-status:dev
              - extensions/slack-build-status:beta
              - extensions/slack-build-status:stable

        volumemounts:
        - name: cache-volume
          mountpath: /cache-volume
          volume:
            emptyDir: {}
        hosts:
        - estafette.secret(ec7-YB_A3z3_ji_i.HrhD2blaZayisApp5GQP0b09VMo7WE0hLjO-wzl4cA3Ta31I5TUhce38CWmAmHi6VN-p2ka1r1KxYwe5)
        internalhosts:
        - estafette.secret(yECTVElecBIrSJ0C.fWucNrbHJS2E9rfmLddw_I_Sc7-bqs3TfWR4-VeZDSkw0uLRewL18OrmTB02mQ4N5_HZ1YQxA0UUCfPBCIZGN-7MGoo=)
