builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team

version:
  semver:
    major: 0
    minor: 0

stages:
  build:
    image: alpine:3.9
    commands:
    - echo "nothing to build here, move along..."

releases:
  tooling:
    stages:
      deploy:
        image: extensions/gke:dev
        kind: statefulset
        replicas: 3
        podManagementpolicy: Parallel
        storageclass: fast
        storagesize: 10Gi
        storagemountpath: /cache-volume
        namespace: estafette
        container:
          port: 5000
          repository: library
          name: registry
          tag: 2.7.1
          env:
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /cache-volume
            REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: inmemory
            REGISTRY_STORAGE_REDIRECT_DISABLE: true
            REGISTRY_STORAGE_DELETE_ENABLED: true
            REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: true
            REGISTRY_HTTP_DEBUG_ADDR: :5001
            REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED: true
          liveness:
            path: /
          readiness:
            path: /
          metrics:
            path: /metrics
            port: 5001
          cpu:
            request: 250m
            limit: 2000m
          memory:
            request: 4096Mi
            limit: 4096Mi
        sidecars:
        - type: openresty
          env:
            PROXY_BUFFERING: 'off'
          cpu:
            request: 100m
            limit: 200m
          memory:
            request: 200Mi
            limit: 200Mi
        - type: heater
          image: estafette/estafette-docker-cache-heater:dev
          env:
            DEBUG: true
            MTU: 1460
            MIRROR: http://localhost:5000
            REGISTRY_HEALTH_ENDPOINT: http://localhost:5001/debug/health
          cpu:
            request: 200m
            limit: 500m
          memory:
            request: 200Mi
            limit: 500Mi
          securityContext:
            privileged: true
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        configs:
          inline:
            container-list.yaml: |
              containers:
              - extensions/prefetch:dev
              - extensions/envvars:dev
              - extensions/git-clone:dev
              - extensions/docker:dev
              - extensions/gke:dev
              - extensions/github-status:dev
              - extensions/bitbucket-status:dev
              - extensions/slack-build-status:dev
              - extensions/npm-audit:dev
              - estafette/cloud-sdk:dev

              - extensions/prefetch:beta
              - extensions/envvars:beta
              - extensions/git-clone:beta
              - extensions/docker:beta
              - extensions/gke:beta
              - extensions/github-status:beta
              - extensions/bitbucket-status:beta
              - extensions/slack-build-status:beta
              - extensions/npm-audit:beta
              - estafette/cloud-sdk:beta

              - extensions/prefetch:stable
              - extensions/envvars:stable
              - extensions/git-clone:stable
              - extensions/docker:stable
              - extensions/gke:stable
              - extensions/github-status:stable
              - extensions/bitbucket-status:stable
              - extensions/slack-build-status:stable
              - extensions/npm-audit:stable
              - estafette/cloud-sdk:stable

              - golang:1.12.5-alpine3.9
              - golang:1.12.6-alpine3.10

              - extensions/dotnet:2.2-stable
              - travix/npm-agent:dubnium-alpine
              - node:dubnium-alpine

        hosts:
        - estafette.secret(ec7-YB_A3z3_ji_i.HrhD2blaZayisApp5GQP0b09VMo7WE0hLjO-wzl4cA3Ta31I5TUhce38CWmAmHi6VN-p2ka1r1KxYwe5)
        internalhosts:
        - estafette.secret(yECTVElecBIrSJ0C.fWucNrbHJS2E9rfmLddw_I_Sc7-bqs3TfWR4-VeZDSkw0uLRewL18OrmTB02mQ4N5_HZ1YQxA0UUCfPBCIZGN-7MGoo=)
