builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team

version:
  semver:
    major: 0
    minor: 0

stages:
  build:
    image: alpine:3.9
    commands:
    - echo "nothing to build here, move along..."

releases:
  tooling:
    actions:
    - name: deploy-canary
    - name: deploy-stable
    - name: rollback-canary
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette
        container:
          port: 5000
          repository: library
          name: registry
          tag: 2.7.1
          env:
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /cache-volume
            REGISTRY_HTTP_DEBUG_ADDR: localhost:5003
          liveness:
            path: /
          readiness:
            path: /
          metrics:
            path: /metrics
            port: 5003
          cpu:
            request: 250m
            limit: 1000m
          memory:
            request: 4096Mi
            limit: 4096Mi
        sidecars:
        - type: openresty
          cpu:
            request: 100m
            limit: 200m
          memory:
            request: 200Mi
            limit: 200Mi
        request:
          timeout: 120s
          maxbodysize: 128M
          clientbodybuffersize: 1m
          proxybuffersnumber: 64
        volumemounts:
        - name: cache-volume
          mountpath: /cache-volume
          volume:
            emptyDir: {}
        hosts:
        - estafette.secret(ec7-YB_A3z3_ji_i.HrhD2blaZayisApp5GQP0b09VMo7WE0hLjO-wzl4cA3Ta31I5TUhce38CWmAmHi6VN-p2ka1r1KxYwe5)
        internalhosts:
        - estafette.secret(yECTVElecBIrSJ0C.fWucNrbHJS2E9rfmLddw_I_Sc7-bqs3TfWR4-VeZDSkw0uLRewL18OrmTB02mQ4N5_HZ1YQxA0UUCfPBCIZGN-7MGoo=)
